"""empty message

Revision ID: 06e9a02c4099
Revises: 
Create Date: 2024-10-12 00:30:54.545052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e9a02c4099'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('food_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('food_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    # ### end Alembic commands ###
