"""empty message

Revision ID: 37c8b3c0144a
Revises: bb0cae3e59af
Create Date: 2024-10-14 18:12:32.858044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c8b3c0144a'
down_revision = 'bb0cae3e59af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_order_food_id', 'menus', ['food_id'], ['food_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_food_id', type_='foreignkey')

    # ### end Alembic commands ###
