"""empty message

Revision ID: 9b97991cdeb9
Revises: 37c8b3c0144a
Create Date: 2024-10-14 18:29:12.934003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b97991cdeb9'
down_revision = '37c8b3c0144a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('food_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('food_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
